// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx0L7TwP3t7O-m7qslmfgw23i1O8GtCxE',
    appId: '1:532660530838:web:1b885b4ffee936938f9cb7',
    messagingSenderId: '532660530838',
    projectId: 'hiot-d7e03',
    authDomain: 'hiot-d7e03.firebaseapp.com',
    databaseURL: 'https://hiot-d7e03-default-rtdb.firebaseio.com',
    storageBucket: 'hiot-d7e03.appspot.com',
    measurementId: 'G-LKMZD6Q3WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWMNHz7uX_T1mSGWaFJv4tm1yAn6XO-QQ',
    appId: '1:532660530838:android:72a13b4fa4a160a18f9cb7',
    messagingSenderId: '532660530838',
    projectId: 'hiot-d7e03',
    databaseURL: 'https://hiot-d7e03-default-rtdb.firebaseio.com',
    storageBucket: 'hiot-d7e03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi7Te02UWNOmTcbhnq78IqCwrPTGoNQN4',
    appId: '1:532660530838:ios:fe0c23d95911550a8f9cb7',
    messagingSenderId: '532660530838',
    projectId: 'hiot-d7e03',
    databaseURL: 'https://hiot-d7e03-default-rtdb.firebaseio.com',
    storageBucket: 'hiot-d7e03.appspot.com',
    iosClientId: '532660530838-0dgj6707geoloso4lsgvveuak280ttda.apps.googleusercontent.com',
    iosBundleId: 'com.example.iotFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi7Te02UWNOmTcbhnq78IqCwrPTGoNQN4',
    appId: '1:532660530838:ios:fe0c23d95911550a8f9cb7',
    messagingSenderId: '532660530838',
    projectId: 'hiot-d7e03',
    databaseURL: 'https://hiot-d7e03-default-rtdb.firebaseio.com',
    storageBucket: 'hiot-d7e03.appspot.com',
    iosClientId: '532660530838-0dgj6707geoloso4lsgvveuak280ttda.apps.googleusercontent.com',
    iosBundleId: 'com.example.iotFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx0L7TwP3t7O-m7qslmfgw23i1O8GtCxE',
    appId: '1:532660530838:web:ddb3efd9bd0144d28f9cb7',
    messagingSenderId: '532660530838',
    projectId: 'hiot-d7e03',
    authDomain: 'hiot-d7e03.firebaseapp.com',
    databaseURL: 'https://hiot-d7e03-default-rtdb.firebaseio.com',
    storageBucket: 'hiot-d7e03.appspot.com',
    measurementId: 'G-HXBPR12QHN',
  );

}